export type BetResult = 'win' | 'loss' | 'push';
export type Sport = 'NRL' | 'AFL' | 'FOOTBALL' | 'OTHER';

export interface LegacyBet {
  id: number;
  date?: string;         // ISO YYYY-MM-DD, only for section-2 bets (283+)
  match: string;
  market: string;
  odds: number | null;
  closingOdds: number | null;
  result: BetResult;
  cumPL: number;
  sport: Sport;
  notes: string;
}

// NRL Betting Model tab — one row per bet with predicted line + CLV data
export interface ModelBet {
  id: number;
  date: string;
  match: string;
  market: string;
  predictedLine: number | null;  // model's predicted line or fair-odds estimate
  takenPrice: number | null;
  closingPrice: number | null;
  result: BetResult;
  plUnits: number;               // individual bet P&L per unit staked
  runningTotal: number;          // cumulative P&L
}

function sport(raw: string | undefined): Sport {
  const s = (raw ?? '').toUpperCase().trim();
  if (s === 'NRL') return 'NRL';
  if (s === 'AFL') return 'AFL';
  if (s === 'FOOTBALL' || s === 'FOOTBAL') return 'FOOTBALL';
  return 'OTHER';
}

function result(raw: string): BetResult {
  const r = raw.toLowerCase().trim();
  if (r === 'win' || r === 'won' || r === 'win ') return 'win';
  if (r === 'loss' || r === 'lost' || r === 'lloss') return 'loss';
  return 'push';
}

// ─── Section 1: Legacy bets (rows 7-282) ────────────────────────────────────
// Inferred sport from team names / comments where not tagged.
// NRL teams: Cowboys, Tigers, Sea Eagles, Storm, Raiders, Roosters, Panthers,
//   Dragons, Knights, Bulldogs, Broncos/Broncoes, Sharks, Titans, Rabbitohs/Rabbitos,
//   Warriors, Dolphins, Eels, Manly, Souths, Canberra, Saints (NRL context)
// AFL teams: Dockers, Pies/Collingwood, Eagles, Saints (AFL), Crows/Adelaide,
//   Hawks/Hawthorn, Power/Port, Giants/GWS, Cats/Geelong, Lions/Brisbane,
//   Demons/Melbourne, Swans/Sydney, Richmond/Tigers (AFL), Bulldogs (AFL),
//   North Melbourne/Kangaroos, St Kilda, West Coast, Fremantle, Gold Coast Suns

export const LEGACY_BETS: LegacyBet[] = [
  { id:1, date:'2025-05-30',  match:'Cowboys vs Tigers',              market:'Total',             odds:null, closingOdds:null, result:'loss', cumPL:-1,    sport:'NRL',      notes:'Weather report changed — line drifted 2-3 points. Missed trading opportunity.' },
  { id:2, date:'2025-07-18',  match:'Sea Eagles vs Storm',            market:'Game',              odds:1.9,  closingOdds:null, result:'loss', cumPL:-2,    sport:'NRL',      notes:'Got the best of it at 1.9. Price came in heavily. Right bet.' },
  { id:3, date:'2025-07-19',  match:'Dockers vs Collingwood',         market:'Trade',             odds:null, closingOdds:null, result:'loss', cumPL:-3,    sport:'AFL',      notes:'Game ended in a draw. Should hedge with $2 on draw.' },
  { id:4, date:'2025-05-31',  match:'Raiders vs Roosters',            market:'Line',              odds:null, closingOdds:null, result:'loss', cumPL:-4,    sport:'NRL',      notes:'Blown out of the water.' },
  { id:5, date:'2025-03-20',  match:'Collingwood vs Bulldogs',        market:'Game (2.5 Dogs)',   odds:2.5,  closingOdds:null, result:'win',  cumPL:-3.85, sport:'AFL',      notes:'Traded off.' },
  { id:6, date:'2025-05-16',  match:'Warriors vs Dolphins',           market:'Game (Dolphins 1.7)', odds:1.7, closingOdds:null, result:'loss', cumPL:-4.85, sport:'NRL',     notes:'Had opportunity to hedge. Didnt.' },
  { id:7, date:'2025-05-16',  match:'Warriors vs Dolphins',           market:'Total Under',       odds:null, closingOdds:null, result:'win',  cumPL:-3.85, sport:'NRL',      notes:'Waited till 55th minute with 4-point buffer. Double-or-nothing in 2nd half.' },
  { id:8, date:'2025-06-25',  match:'Port vs Carlton',               market:'Total Under 170.5', odds:null, closingOdds:null, result:'loss', cumPL:-4.85, sport:'AFL',      notes:'Wind died. Monitor weather changes.' },
  { id:9, date:'2025-07-31',  match:'Hawthorn vs Adelaide',          market:'Game 2.3',          odds:2.3,  closingOdds:null, result:'win',  cumPL:-3.85, sport:'AFL',      notes:'Traded off.' },
  { id:10, date:'2025-06-22', match:'Roosters vs Cowboys',           market:'Handicap +19.5',    odds:null, closingOdds:null, result:'win',  cumPL:-2.85, sport:'NRL',      notes:'Good pick. May trade off.' },
  { id:11, date:'2025-06-22', match:'Roosters vs Cowboys',           market:'Game 7.20',         odds:7.2,  closingOdds:null, result:'win',  cumPL: 0.35, sport:'NRL',      notes:'Free bet.' },
  { id:12, date:'2025-06-22', match:'Roosters vs Cowboys',           market:'Total Under 53.5',  odds:null, closingOdds:null, result:'win',  cumPL: 1.35, sport:'NRL',      notes:'Easy money. Bog ground.' },
  { id:13, date:'2026-03-27', match:'Knights vs Bulldogs',           market:'Total Over 41.5',   odds:null, closingOdds:null, result:'loss', cumPL: 0.35, sport:'NRL',      notes:'Got the weather wrong. Rain didnt come.' },
  { id:14, date:'2026-04-25', match:'Eagles vs Saints',              market:'Total Over 153.5',  odds:null, closingOdds:null, result:'loss', cumPL:-0.65, sport:'AFL',      notes:'First quarter did it. Opportunity to trade out at 3/4 time.' },
  { id:15, date:'2026-04-25', match:'Eagles vs Saints',              market:'Game 1.8',          odds:1.8,  closingOdds:null, result:'win',  cumPL: 0.35, sport:'AFL',      notes:'Saints losing first half, came back well.' },
  { id:16, date:'2025-09-05', match:'Panthers vs Saints',            market:'Total Under 43.5',  odds:null, closingOdds:null, result:'win',  cumPL: 1.35, sport:'NRL',      notes:'Easy money. Raining.' },
  { id:17, date:'2025-05-02', match:'Dragons vs Tigers',             market:'Total Under 47.5',  odds:null, closingOdds:null, result:'loss', cumPL: 0.35, sport:'NRL',      notes:'Should have got off. Good playing surface.' },
  { id:18, date:'2025-06-07', match:'Eagles vs North Melbourne',     market:'Total Over 150.5 1.7', odds:1.7, closingOdds:null, result:'loss', cumPL:-0.65, sport:'AFL',   notes:'Right bet. West Coast could not kick straight.' },
  { id:19, date:'2025-06-21', match:'Broncos vs Sharks',             market:'Game +6.5',         odds:null, closingOdds:null, result:'win',  cumPL: 0.35, sport:'NRL',      notes:'Right bet. State of Origin hangover.' },
  { id:20, date:'2025-08-09', match:'Titans vs Rabbitohs',           market:'Total Under 55.5 1.83', odds:1.83, closingOdds:null, result:'push', cumPL: 0.35, sport:'NRL', notes:'Nearly got it.' },
  { id:21, date:'2025-05-03', match:'Cowboys vs Warriors',           market:'Game 2.3',          odds:2.3,  closingOdds:null, result:'win',  cumPL: 1.35, sport:'NRL',      notes:'Excellent bet. State of Origin hangover.' },
  { id:22, date:'2025-07-03', match:'Collingwood vs Carlton',        market:'Game 2.2',          odds:2.2,  closingOdds:null, result:'win',  cumPL: 2.35, sport:'AFL',      notes:'Traded off.' },
  { id:23, date:'2025-08-20', match:'Essendon vs Carlton',           market:'Game 2.6',          odds:2.6,  closingOdds:null, result:'loss', cumPL: 1.35, sport:'AFL',      notes:'Right bet. Too many bets overall — be more selective.' },
  { id:24, date:'2026-03-20', match:'Sharks vs Dolphins',            market:'Handicap +9.5',     odds:null, closingOdds:null, result:'win',  cumPL: 2.35, sport:'NRL',      notes:'Good bet.' },
  { id:25, date:'2025-09-06', match:'Tigers vs Titans',              market:'Total Under 51.5',  odds:null, closingOdds:null, result:'push', cumPL: 2.35, sport:'NRL',      notes:'Wait until at least half time. Must be a rule.' },
  { id:26, date:'2026-04-10', match:'Warriors vs Storm',             market:'Game 1.94',         odds:1.94, closingOdds:null, result:'win',  cumPL: 3.35, sport:'NRL',      notes:'Against the crowd. Only 50% of late money gets up.' },
  { id:28, date:'2025-05-23', match:'Kangaroos vs Collingwood',      market:'Handicap +38.5',    odds:null, closingOdds:null, result:'win',  cumPL: 3.35, sport:'AFL',      notes:'Should have waited. Dogs usually come in late.' },
  { id:29, date:'2025-06-06', match:'GWS vs Port Adelaide',          market:'Game 2.5',          odds:2.5,  closingOdds:null, result:'loss', cumPL: 2.35, sport:'AFL',      notes:'Fair bet. Could have laid off.' },
  { id:30, date:'2025-06-06', match:'GWS vs Port Adelaide',          market:'Total 1.85',        odds:1.85, closingOdds:null, result:'win',  cumPL: 3.35, sport:'AFL',      notes:'Good in-play bet. Both teams kicking behinds.' },
  { id:31, date:'2025-07-24', match:'GWS vs Sydney',                 market:'Half 2.25',         odds:2.25, closingOdds:null, result:'loss', cumPL: 2.35, sport:'AFL',      notes:'Injuries. Must factor in injury list going forward.' },
  { id:32, date:'2026-04-30', match:'Dolphins vs Storm',             market:'Game 2.83',         odds:2.83, closingOdds:null, result:'loss', cumPL: 1.35, sport:'NRL',      notes:'Right bet. Could have traded at half time if watching live.' },
  { id:33, date:'2025-08-15', match:'Roosters vs Bulldogs',          market:'Total Under 50.5',  odds:null, closingOdds:null, result:'win',  cumPL: 2.35, sport:'NRL',      notes:'Easy money.' },
  { id:34, date:'2026-04-16', match:'GWS vs Sydney',                 market:'Total Under 170.5', odds:null, closingOdds:null, result:'loss', cumPL: 1.35, sport:'AFL',      notes:'Right bet. Both teams kick extremely straight.' },
  { id:35, date:'2025-05-28', match:'Blues vs Maroons',              market:'Game 1.92',         odds:1.92, closingOdds:null, result:'win',  cumPL: 2.35, sport:'NRL',      notes:'Good bet.' },
  { id:36, date:'2026-04-18', match:'Brisbane vs Melbourne',         market:'Total Over 168.5',  odds:null, closingOdds:null, result:'loss', cumPL: 1.35, sport:'AFL',      notes:'Right bet. Need to figure out lay-off at quarter time.' },
  { id:37, date:'2025-06-28', match:'Warriors vs Broncos',           market:'Game 2.27',         odds:2.27, closingOdds:null, result:'win',  cumPL: 2.35, sport:'NRL',      notes:'Origin time.' },
  { id:38, date:'2025-07-02', match:'Kangaroos vs Bulldogs',         market:'Game 6.75',         odds:6.75, closingOdds:null, result:'loss', cumPL: 1.35, sport:'AFL',      notes:'Right bet. Could not get it over the line.' },
  { id:39, date:'2026-04-11', match:'Saints vs Port Adelaide',       market:'Game 2.24',         odds:2.24, closingOdds:null, result:'win',  cumPL: 2.35, sport:'AFL',      notes:'Must win for Power.' },
  { id:40, date:'2026-04-16', match:'Storm vs Canberra',             market:'Game 5',            odds:5,    closingOdds:null, result:'loss', cumPL: 1.35, sport:'NRL',      notes:'Right bet.' },
  { id:42, date:'2025-07-12', match:'Saints vs Sydney',              market:'Total Over 168.5',  odds:null, closingOdds:null, result:'loss', cumPL: 1.35, sport:'AFL',      notes:'Right bet. 4 points off.' },
  { id:43, date:'2026-04-15', match:'Collingwood vs Carlton',        market:'Game 2.12',         odds:2.12, closingOdds:null, result:'loss', cumPL: 0.35, sport:'AFL',      notes:'Pies in poor form.' },
  { id:44, date:'2026-04-15', match:'Collingwood vs Carlton',        market:'Game 2.6',          odds:2.6,  closingOdds:null, result:'win',  cumPL: 1.35, sport:'AFL',      notes:'Must win for Pies.' },
  { id:45, date:'2025-07-23', match:'Carlton vs Hawthorn',           market:'Game 2',            odds:2,    closingOdds:null, result:'loss', cumPL: 0.35, sport:'AFL',      notes:'Must win for Carlton. Hunch bet.' },
  { id:46, date:'2025-07-30', match:'GWS vs Bulldogs',               market:'Game 2.8',          odds:2.8,  closingOdds:null, result:'loss', cumPL:-0.65, sport:'AFL',      notes:'Did not look at the game well enough.' },
  { id:47, date:'2025-05-25', match:'Arsenal vs Southampton',        market:'Draw 5',            odds:5,    closingOdds:null, result:'loss', cumPL:-1.65, sport:'FOOTBALL', notes:'' },
  { id:48, date:'2025-08-23', match:'Man City vs Tottenham',         market:'Draw 5',            odds:5,    closingOdds:null, result:'loss', cumPL:-2.65, sport:'FOOTBALL', notes:'' },
  { id:49, date:'2026-04-17', match:'Port Adelaide vs Hawthorn',     market:'Game 3',            odds:3,    closingOdds:null, result:'win',  cumPL:-1.65, sport:'AFL',      notes:'' },
  { id:51, date:'2025-06-28', match:'Warriors vs Broncos',           market:'Game 3.1',          odds:3.1,  closingOdds:null, result:'win',  cumPL: 0.35, sport:'NRL',      notes:'' },
  { id:52, date:'2026-04-02', match:'Bulldogs vs Rabbitohs',         market:'Game 3.5',          odds:3.5,  closingOdds:null, result:'loss', cumPL:-0.65, sport:'NRL',      notes:'' },
  { id:53, date:'2026-04-24', match:'Roosters vs Dragons',           market:'Under 45.5',        odds:2,    closingOdds:1.95, result:'loss', cumPL:-1.65, sport:'NRL',      notes:'' },
  { id:54, date:'2026-05-02', match:'Panthers vs Manly',             market:'Under 46.5',        odds:2,    closingOdds:2,    result:'win',  cumPL:-0.65, sport:'NRL',      notes:'' },
  { id:55, date:'2025-04-26', match:'Carlton vs Geelong',            market:'Carlton +11.5',     odds:1.9,  closingOdds:null, result:'win',  cumPL: 0.35, sport:'AFL',      notes:'' },
  { id:56, date:'2025-04-26', match:'Canberra vs Dolphins',          market:'Dolphins +6.5',     odds:1.95, closingOdds:null, result:'loss', cumPL:-0.65, sport:'NRL',      notes:'' },
  { id:57, date:'2025-05-02', match:'Western Bulldogs vs Port Adelaide', market:'Port Adelaide 3.2', odds:3.2, closingOdds:null, result:'loss', cumPL:-1.65, sport:'AFL',  notes:'' },
  { id:58, date:'2025-05-02', match:'Geelong vs Collingwood',        market:'Geelong +11.5',     odds:null, closingOdds:null, result:'loss', cumPL:-2.65, sport:'AFL',      notes:'' },
  { id:59, date:'2025-05-03', match:'Sydney vs GWS',                 market:'Sydney 2.4',        odds:2.4,  closingOdds:null, result:'win',  cumPL:-1.65, sport:'AFL',      notes:'' },
  { id:60, date:'2025-05-03', match:'Brisbane vs Gold Coast',        market:'Gold Coast (trade)', odds:null, closingOdds:null, result:'loss', cumPL:-2.65, sport:'AFL',     notes:'' },
  { id:61, date:'2025-05-07', match:'Collingwood vs Fremantle',      market:'Collingwood',       odds:1.7,  closingOdds:1.8,  result:'win',  cumPL:-1.65, sport:'AFL',      notes:'Data proves 5-day turnaround not bad. 7.5% edge.' },
  { id:62, date:'2025-05-09', match:'Cowboys vs Panthers',           market:'Cowboys',           odds:2.3,  closingOdds:2.55, result:'push', cumPL:-1.65, sport:'NRL',      notes:'People overestimated Panthers. 7-10% edge.' },
  { id:63, date:'2025-05-10', match:'Richmond vs West Coast',        market:'Richmond',          odds:null, closingOdds:1.5,  result:'win',  cumPL:-0.65, sport:'AFL',      notes:'Full moon. 7.5% edge.' },
  { id:64, date:'2025-05-10', match:'North Melbourne vs Brisbane',   market:'Total Over 175',    odds:null, closingOdds:1.9,  result:'loss', cumPL:-1.65, sport:'AFL',      notes:'Full moon. 7.5% edge.' },
  { id:65, date:'2025-05-15', match:'Sydney vs Carlton',             market:'Total Under 163.5', odds:null, closingOdds:null, result:'win',  cumPL:-0.65, sport:'AFL',      notes:'' },
  { id:66, date:'2025-05-16', match:'Collingwood vs Adelaide',       market:'Adelaide +11.5',    odds:null, closingOdds:1.8,  result:'win',  cumPL: 0.35, sport:'AFL',      notes:'' },
  { id:67, date:'2025-05-16', match:'GWS vs Fremantle',              market:'Live Fremantle Win', odds:null, closingOdds:null, result:'win', cumPL: 1.35, sport:'AFL',       notes:'' },
  { id:68, date:'2025-05-17', match:'Tigers vs Rabbitohs',           market:'Total Under 45.5',  odds:null, closingOdds:null, result:'win',  cumPL: 2.35, sport:'NRL',      notes:'' },
  { id:69, date:'2025-05-17', match:'Broncos vs Dragons',            market:'Broncos +11.5',     odds:null, closingOdds:null, result:'loss', cumPL: 1.35, sport:'NRL',      notes:'Hunch bet. No more hunches — purely data driven.' },
  { id:70, date:'2025-05-21', match:'Geelong vs Bulldogs',           market:'BT -15 (2.5)',      odds:2.5,  closingOdds:null, result:'win',  cumPL: 2.35, sport:'AFL',      notes:'' },
  { id:71, date:'2025-05-21', match:'Bulldogs vs Dolphins',          market:'Total Under 44.5',  odds:null, closingOdds:null, result:'loss', cumPL: 1.35, sport:'NRL',      notes:'Drifted all week — get on right at the end when edge is in your favour.' },
  { id:72, date:'2025-05-23', match:'Penrith vs Newcastle',          market:'Total Under 44.5',  odds:null, closingOdds:null, result:'win',  cumPL: 2.35, sport:'NRL',      notes:'Comeback wins even from bad half-time position.' },
  { id:73, date:'2025-05-24', match:'Melbourne vs Sydney',           market:'Total Under 168.5', odds:null, closingOdds:null, result:'loss', cumPL: 1.35, sport:'AFL',      notes:'Game opened up after half time.' },
  { id:74, date:'2025-05-28', match:'QLD vs NSW',                    market:'QLD 2.23',          odds:2.23, closingOdds:null, result:'loss', cumPL: 0.35, sport:'NRL',      notes:'' },
  { id:75, date:'2025-05-30', match:'Titans vs Storm',               market:'Total Under 51.5',  odds:1.9,  closingOdds:null, result:'win',  cumPL: 1.35, sport:'NRL',      notes:'' },
  { id:76, date:'2025-05-30', match:'Cowboys vs Tigers',             market:'Total Over 49.5',   odds:1.9,  closingOdds:null, result:'win',  cumPL: 2.35, sport:'NRL',      notes:'' },
  { id:77, date:'2025-05-30', match:'Sydney vs Adelaide',            market:'Adelaide +5.5',     odds:1.9,  closingOdds:null, result:'win',  cumPL: 3.35, sport:'AFL',      notes:'' },
  { id:78, date:'2025-05-30', match:'Manly vs Brisbane',             market:'Manly',             odds:2.5,  closingOdds:null, result:'win',  cumPL: 5.35, sport:'NRL',      notes:'' },
  { id:79, date:'2025-05-31', match:'Titans vs Melbourne',           market:'Titans +13.5',      odds:1.9,  closingOdds:null, result:'win',  cumPL: 6.35, sport:'NRL',      notes:'Killing it!' },
  { id:80, date:'2025-05-31', match:'West Coast vs Geelong',         market:'Total Over 171.5',  odds:1.9,  closingOdds:null, result:'win',  cumPL: 7.35, sport:'AFL',      notes:'' },
  { id:81, date:'2025-05-31', match:'PSG vs Inter',                  market:'Inter',             odds:3.6,  closingOdds:null, result:'loss', cumPL: 6.35, sport:'FOOTBALL', notes:'' },
  { id:82, date:'2025-06-05', match:'Adelaide vs Brisbane',          market:'Total Under 158.5', odds:null, closingOdds:null, result:'win',  cumPL: 7.35, sport:'AFL',      notes:'' },
  { id:83, date:'2025-06-05', match:'Storm vs Cowboys',              market:'Cowboys +14.5',     odds:1.95, closingOdds:null, result:'loss', cumPL: 7.85, sport:'NRL',      notes:'' },
  { id:84, date:'2025-06-05', match:'Storm vs Cowboys',              market:'Total Over 51.5',   odds:2,    closingOdds:null, result:'win',  cumPL: 6.85, sport:'NRL',      notes:'' },
  { id:85, date:'2025-06-06', match:'Broncos vs Titans',             market:'Total Over 51.5',   odds:null, closingOdds:null, result:'win',  cumPL: 7.85, sport:'NRL',      notes:'' },
  { id:86, date:'2025-06-07', match:'Tigers vs Panthers',            market:'Total Under 47.5',  odds:null, closingOdds:null, result:'win',  cumPL: 8.85, sport:'NRL',      notes:'' },
  { id:87, date:'2025-06-08', match:'Eels vs Bulldogs',              market:'Total Under 46.5',  odds:null, closingOdds:null, result:'loss', cumPL: 7.85, sport:'NRL',      notes:'' },
  { id:88, date:'2025-06-08', match:'Melbourne vs Collingwood',      market:'Total Under 156.5', odds:null, closingOdds:null, result:'win',  cumPL: 8.35, sport:'AFL',      notes:'' },
  { id:89, date:'2025-06-08', match:'Melbourne vs Collingwood',      market:'Melbourne +23.5',   odds:null, closingOdds:null, result:'win',  cumPL: 9.35, sport:'AFL',      notes:'' },
  { id:90, date:'2025-06-11', match:'Western Bulldogs vs St Kilda',  market:'Bulldogs +24.5',    odds:null, closingOdds:null, result:'loss', cumPL: 8.35, sport:'AFL',      notes:'' },
  { id:91, date:'2025-06-12', match:'Hawthorn vs Adelaide',          market:'Hawthorn 1.83',     odds:1.83, closingOdds:null, result:'win',  cumPL: 9.35, sport:'AFL',      notes:'' },
  { id:92, date:'2025-06-13', match:'Brisbane vs GWS',               market:'Total Under 168.5', odds:1.9,  closingOdds:null, result:'loss', cumPL: 8.35, sport:'AFL',      notes:'' },
  { id:93, date:'2025-06-14', match:'Port Adelaide vs Melbourne',    market:'Either Team',       odds:2.45, closingOdds:null, result:'loss', cumPL: 7.35, sport:'AFL',      notes:'' },
  { id:94, date:'2025-06-14', match:'Rabbitohs vs Bulldogs',         market:'Rabbitohs +8.5',    odds:1.8,  closingOdds:null, result:'win',  cumPL: 8.35, sport:'NRL',      notes:'' },
  { id:95, date:'2025-06-18', match:'QLD vs NSW',                    market:'QLD 3.06',          odds:3.06, closingOdds:null, result:'win',  cumPL:10.35, sport:'NRL',      notes:'' },
  { id:96, date:'2025-06-18', match:'QLD vs NSW',                    market:'Total Under 41.5',  odds:null, closingOdds:null, result:'loss', cumPL: 9.35, sport:'NRL',      notes:'' },
  { id:97, date:'2025-06-19', match:'Geelong vs Brisbane',           market:'Brisbane 3',        odds:3,    closingOdds:null, result:'win',  cumPL:10.35, sport:'AFL',      notes:'' },
  { id:98, date:'2025-06-21', match:'Broncos vs Sharks',             market:'Under 48.5',        odds:null, closingOdds:null, result:'loss', cumPL: 9.35, sport:'NRL',      notes:'' },
  { id:99, date:'2025-06-20', match:'Port Adelaide vs Sydney',       market:'Under 168.5',       odds:null, closingOdds:null, result:'win',  cumPL:10.35, sport:'AFL',      notes:'' },
  { id:100, date:'2025-06-21',match:'Roosters vs Cowboys',           market:'Cowboys 3',         odds:3,    closingOdds:null, result:'loss', cumPL: 9.35, sport:'NRL',      notes:'' },
  { id:101, date:'2025-06-25',match:'Panthers vs Bulldogs',          market:'Total Under 42.5',  odds:null, closingOdds:null, result:'win',  cumPL:10.35, sport:'NRL',      notes:'' },
  { id:102, date:'2025-06-25',match:'Port Adelaide vs Carlton',      market:'Port Adelaide -4.5', odds:null, closingOdds:null, result:'win', cumPL:11.35, sport:'AFL',      notes:'' },
  { id:103, date:'2025-06-26',match:'Sydney vs Western Bulldogs',    market:'Bulldogs -9.5',     odds:null, closingOdds:null, result:'loss', cumPL:10.35, sport:'AFL',      notes:'' },
  { id:104, date:'2025-06-27',match:'Collingwood vs West Coast',     market:'Total Under 172.5', odds:null, closingOdds:null, result:'win',  cumPL:11.35, sport:'AFL',      notes:'' },
  { id:105, date:'2025-06-27',match:'Broncos vs Warriors',           market:'Warriors',          odds:2.5,  closingOdds:null, result:'loss', cumPL:10.35, sport:'NRL',      notes:'' },
  { id:106, date:'2025-06-28',match:'Titans vs Cowboys',             market:'Total Under 50.5',  odds:null, closingOdds:null, result:'loss', cumPL: 9.35, sport:'NRL',      notes:'' },
  { id:108, date:'2025-07-03',match:'Bulldogs vs Broncos',           market:'Bulldogs 1.4',      odds:1.4,  closingOdds:null, result:'loss', cumPL: 7.85, sport:'NRL',      notes:'' },
  { id:109, date:'2025-07-03',match:'Carlton vs Collingwood',        market:'Carlton +30.5',     odds:1.9,  closingOdds:null, result:'loss', cumPL: 6.85, sport:'AFL',      notes:'' },
  { id:110, date:'2025-07-04',match:'Geelong vs Richmond',           market:'Under 176.5',       odds:1.9,  closingOdds:null, result:'win',  cumPL: 7.85, sport:'AFL',      notes:'' },
  { id:111, date:'2025-07-05',match:'Sydney vs Fremantle',           market:'Fremantle +7.5',    odds:1.9,  closingOdds:null, result:'loss', cumPL: 6.85, sport:'AFL',      notes:'' },
  { id:112, date:'2025-07-05',match:'Cowboys vs Storm',              market:'Over 47.5',         odds:1.9,  closingOdds:null, result:'loss', cumPL: 5.85, sport:'NRL',      notes:'' },
  { id:113, date:'2025-07-06', match:'Manly vs South Sydney',         market:'Souths 3.75',       odds:3.75, closingOdds:null, result:'loss', cumPL: 4.85, sport:'NRL',      notes:'' },
  { id:114, date:'2025-07-09', match:'PSG vs Real Madrid',            market:'PSG 2.4',           odds:2.4,  closingOdds:null, result:'win',  cumPL: 6.25, sport:'FOOTBALL', notes:'' },
  { id:115, date:'2025-07-11',match:'Fremantle vs Hawthorn',         market:'Over 154.5',        odds:1.9,  closingOdds:null, result:'loss', cumPL: 5.25, sport:'AFL',      notes:'' },
  { id:116, date:'2025-07-11',match:'GWS vs Geelong',                market:'Under 171.5',       odds:1.9,  closingOdds:null, result:'loss', cumPL: 4.25, sport:'AFL',      notes:'' },
  { id:117, date:'2025-07-11',match:'GWS vs Geelong',                market:'Under 178.5',       odds:1.9,  closingOdds:null, result:'loss', cumPL: 3.25, sport:'AFL',      notes:'' },
  { id:118, date:'2025-07-12',match:'St Kilda vs Sydney',            market:'Under 167.5',       odds:1.9,  closingOdds:null, result:'loss', cumPL: 2.25, sport:'AFL',      notes:'' },
  { id:119, date:'2025-07-13', match:'PSG vs Chelsea',                market:'Plus 1',            odds:2,    closingOdds:null, result:'loss', cumPL: 1.25, sport:'FOOTBALL', notes:'' },
  { id:120, date:'2025-07-12',match:'Eels vs Panthers',              market:'Under 46.5',        odds:1.9,  closingOdds:null, result:'win',  cumPL: 2.25, sport:'NRL',      notes:'' },
  { id:121, date:'2025-07-12',match:'Titans vs Broncos',             market:'Over 51.5',         odds:1.9,  closingOdds:null, result:'loss', cumPL: 1.25, sport:'NRL',      notes:'' },
  { id:122, date:'2025-07-18',match:'Hawthorn vs Port Adelaide',     market:'Over 156.5',        odds:1.9,  closingOdds:null, result:'loss', cumPL: 0.25, sport:'AFL',      notes:'' },
  { id:123, date:'2025-07-18',match:'Carlton vs Melbourne',          market:'Under 165.5',       odds:1.9,  closingOdds:null, result:'win',  cumPL: 1.25, sport:'AFL',      notes:'' },
  { id:124, date:'2025-07-19',match:'Adelaide vs Gold Coast',        market:'Under 165.5',       odds:1.9,  closingOdds:null, result:'win',  cumPL: 2.25, sport:'AFL',      notes:'' },
  { id:125, date:'2025-07-23',match:'Hawthorn vs Carlton',           market:'Under 160.5',       odds:1.9,  closingOdds:null, result:'win',  cumPL: 3.25, sport:'AFL',      notes:'' },
  { id:126, date:'2025-07-24',match:'Broncos vs Parramatta',         market:'Over 47.5',         odds:1.9,  closingOdds:null, result:'loss', cumPL: 2.25, sport:'NRL',      notes:'Missed by 5 points.' },
  { id:127, date:'2026-03-27',match:'Panthers vs Eels',              market:'Under 47.5',        odds:1.9,  closingOdds:null, result:'win',  cumPL: 3.25, sport:'NRL',      notes:'' },
  { id:128, date:'2025-09-12',match:'Gold Coast vs Brisbane',        market:'Under 154.5',       odds:1.9,  closingOdds:null, result:'loss', cumPL: 2.25, sport:'AFL',      notes:'Rain came at half time, game mostly over by then.' },
  { id:129, date:'2026-04-30',match:'Adelaide vs Port Adelaide',     market:'Under 149.5',       odds:1.9,  closingOdds:null, result:'loss', cumPL: 1.25, sport:'AFL',      notes:'Windy and rainy yet game still wasnt a factor.' },
  { id:130, date:'2025-09-11',match:'Hawthorn vs Adelaide',          market:'Under 165.5',       odds:1.9,  closingOdds:null, result:'loss', cumPL: 0.25, sport:'AFL',      notes:'' },
  { id:131, date:'2025-09-19',match:'Collingwood vs Brisbane',       market:'Under 164.5',       odds:1.9,  closingOdds:null, result:'win',  cumPL: 1.25, sport:'AFL',      notes:'' },
  { id:132, date:'2026-04-24',match:'Fremantle vs Carlton',          market:'Under 159.5',       odds:1.9,  closingOdds:null, result:'loss', cumPL: 0.25, sport:'AFL',      notes:'' },
  { id:133, date:'2025-08-02',match:'Tigers vs Bulldogs',            market:'Under 42.5',        odds:1.9,  closingOdds:null, result:'win',  cumPL: 1.25, sport:'NRL',      notes:'' },
  { id:134, date:'2025-08-08',match:'Port Adelaide vs Fremantle',    market:'Under 166.5',       odds:1.9,  closingOdds:null, result:'loss', cumPL: 0.25, sport:'AFL',      notes:'' },
  { id:135, date:'2025-08-08',match:'Knights vs Panthers',           market:'Under 46.5',        odds:1.9,  closingOdds:null, result:'loss', cumPL:-0.75, sport:'NRL',      notes:'' },
  { id:136, date:'2025-08-14',match:'Fremantle vs Brisbane',         market:'Under 168.5',       odds:1.9,  closingOdds:null, result:'win',  cumPL: 0.25, sport:'AFL',      notes:'' },
  { id:137, date:'2025-08-17', match:'Chelsea vs Crystal Palace',     market:'Draw 4.2',          odds:4.2,  closingOdds:null, result:'loss', cumPL:-0.75, sport:'FOOTBALL', notes:'' },
  { id:138, date:'2025-08-17', match:'Man United vs Arsenal',         market:'Draw 3.4',          odds:3.4,  closingOdds:1.4,  result:'win',  cumPL: 1.75, sport:'FOOTBALL', notes:'' },
  { id:139, date:'2025-08-21',match:'Collingwood vs Melbourne',      market:'Under 165.5',       odds:1.9,  closingOdds:null, result:'win',  cumPL: 2.75, sport:'AFL',      notes:'' },
  { id:140, date:'2025-08-21',match:'Rabbitohs vs Dragons',          market:'Under 46.5',        odds:1.9,  closingOdds:null, result:'win',  cumPL: 3.75, sport:'NRL',      notes:'' },
  { id:141, date:'2025-08-21',match:'Penrith vs Raiders',            market:'Under 42.5',        odds:1.9,  closingOdds:null, result:'win',  cumPL: 4.75, sport:'NRL',      notes:'' },
  { id:142, date:'2025-08-24', match:'Crystal Palace vs Nottingham',  market:'Draw/Notts 1.7',    odds:1.7,  closingOdds:null, result:'win',  cumPL: 5.45, sport:'FOOTBALL', notes:'90 units in, 7.4% return. Goal is 15%.' },
  { id:143, date:'2025-08-30', match:'Man United vs Burnley',         market:'Man U 1.4',         odds:1.4,  closingOdds:null, result:'win',  cumPL: 5.85, sport:'FOOTBALL', notes:'' },
  { id:144, date:'2025-08-31', match:'Liverpool vs Arsenal',          market:'Liverpool 2.3',     odds:2.3,  closingOdds:1.3,  result:'win',  cumPL: 7.05, sport:'FOOTBALL', notes:'' },
  { id:145, date:'2025-08-30', match:'Leeds vs Newcastle',            market:'Draw/Leeds 1.8',    odds:1.8,  closingOdds:null, result:'win',  cumPL: 7.85, sport:'FOOTBALL', notes:'' },
  { id:146, date:'2025-09-03',match:'Adelaide vs Collingwood',       market:'Collingwood 2.4',   odds:2.4,  closingOdds:null, result:'win',  cumPL: 9.25, sport:'AFL',      notes:'' },
  { id:147, date:'2025-09-04',match:'Geelong vs Brisbane',           market:'Brisbane 2.3',      odds:2.3,  closingOdds:null, result:'loss', cumPL: 8.25, sport:'AFL',      notes:'' },
  { id:148, date:'2025-09-11',match:'Adelaide vs Hawthorn',          market:'Adelaide 1.9',      odds:1.9,  closingOdds:null, result:'loss', cumPL: 7.25, sport:'AFL',      notes:'' },
  { id:149, date:'2025-09-13',match:'Canberra vs Broncos',           market:'Line 2.5',          odds:1.9,  closingOdds:null, result:'loss', cumPL: 6.25, sport:'NRL',      notes:'' },
  { id:150, date:'2025-09-12',match:'Brisbane vs Gold Coast',        market:'Line 8.5',          odds:1.9,  closingOdds:null, result:'win',  cumPL: 7.25, sport:'AFL',      notes:'' },
  { id:151, date:'2025-09-12',match:'Warriors vs Panthers',          market:'Line 9.5',          odds:1.9,  closingOdds:null, result:'loss', cumPL: 6.25, sport:'NRL',      notes:'' },
  { id:152, date:'2025-09-17', match:'Liverpool vs Atletico Madrid',  market:'Liverpool 1.5',     odds:1.5,  closingOdds:null, result:'win',  cumPL: 6.75, sport:'FOOTBALL', notes:'' },
  { id:153, date:'2025-09-19',match:'Brisbane vs Collingwood',       market:'Under 163.5',       odds:1.9,  closingOdds:null, result:'loss', cumPL: 5.75, sport:'AFL',      notes:'Wet, new moon, final footie.' },
  { id:154, date:'2025-09-19',match:'Canberra vs Cronulla',          market:'Canberra 1.8',      odds:1.8,  closingOdds:null, result:'loss', cumPL: 4.75, sport:'NRL',      notes:'' },
  { id:155, date:'2025-09-20', match:'Liverpool vs Everton',          market:'Liverpool 1.5',     odds:1.5,  closingOdds:null, result:'win',  cumPL: 5.25, sport:'FOOTBALL', notes:'' },
  { id:156, date:'2025-09-21', match:'Bournemouth vs Newcastle',      market:'Bournemouth 2.45',  odds:2.45, closingOdds:1.45, result:'push', cumPL: 5.25, sport:'FOOTBALL', notes:'' },
  { id:157, date:'2025-09-21', match:'Arsenal vs Man City',           market:'Arsenal 1.95',      odds:1.95, closingOdds:null, result:'loss', cumPL: 4.25, sport:'FOOTBALL', notes:'' },
  { id:158, date:'2025-09-19',match:'Bulldogs vs Panthers',          market:'Bulldogs +8.5',     odds:1.95, closingOdds:null, result:'loss', cumPL: 3.25, sport:'NRL',      notes:'' },
  { id:159, date:'2025-09-27', match:'Liverpool vs Crystal Palace',   market:'Liverpool 1.9',     odds:1.9,  closingOdds:null, result:'loss', cumPL: 2.25, sport:'FOOTBALL', notes:'' },
  { id:161, date:'2025-09-27',match:'Broncos vs Panthers',           market:'Broncos 1.9',       odds:1.9,  closingOdds:null, result:'win',  cumPL:3.25, sport:'NRL',      notes:'' },
  { id:162, date:'2025-09-27',match:'Broncos vs Panthers',           market:'Under 49.5',        odds:1.9,  closingOdds:null, result:'win',  cumPL:4.15, sport:'NRL',      notes:'' },
  { id:164, date:'2025-10-04', match:'Leeds vs Tottenham',            market:'Win/Draw Leeds 3.4', odds:3.4, closingOdds:1.4,  result:'loss', cumPL:3.15, sport:'FOOTBALL', notes:'' },
  { id:165, date:'2025-10-04', match:'Liverpool vs Chelsea',          market:'Draw 3.8',          odds:3.8,  closingOdds:1.8,  result:'win',  cumPL:4.15, sport:'FOOTBALL', notes:'' },
  { id:166, date:'2026-04-18',match:'Brisbane vs Melbourne',         market:'Win 4.2',           odds:4.2,  closingOdds:null, result:'win',  cumPL:7.35, sport:'AFL',      notes:'Live bet.' },
  { id:167, date:'2025-10-05', match:'Brentford vs Man City',         market:'Draw 4.3',          odds:4.3,  closingOdds:1.3,  result:'loss', cumPL:6.35, sport:'FOOTBALL', notes:'' },
  { id:168, date:'2025-10-19', match:'Liverpool vs Man United',       market:'Liverpool 1.64',    odds:1.64, closingOdds:null, result:'loss', cumPL:5.35, sport:'FOOTBALL', notes:'' },
  { id:169, date:'2025-10-26', match:'Arsenal vs Crystal Palace',     market:'Draw 4.5',          odds:4.5,  closingOdds:null, result:'loss', cumPL:4.35, sport:'FOOTBALL', notes:'' },
  { id:171, date:'2025-10-26', match:'Everton vs Tottenham',          market:'Draw 3.5',          odds:3.5,  closingOdds:null, result:'loss', cumPL:2.35, sport:'FOOTBALL', notes:'' },
  { id:172, date:'2025-11-01', match:'Crystal Palace vs Brentford',   market:'Brentford 4',       odds:4,    closingOdds:1.6,  result:'loss', cumPL:1.35, sport:'FOOTBALL', notes:'' },
  { id:173, date:'2025-11-02', match:'West Ham vs Newcastle',         market:'Newcastle 1.7',     odds:1.7,  closingOdds:null, result:'loss', cumPL:0.35, sport:'FOOTBALL', notes:'' },
  { id:174, date:'2025-12-07', match:'West Ham vs Brighton',          market:'Draw 4.7',          odds:4.7,  closingOdds:3.7,  result:'win',  cumPL:4.05, sport:'FOOTBALL', notes:'' },
  { id:175, date:'2025-12-06', match:'Arsenal vs Aston Villa',        market:'Aston Villa 1.3',   odds:1.3,  closingOdds:2,    result:'win',  cumPL:6.05, sport:'FOOTBALL', notes:'' },
  { id:176, date:'2025-12-06', match:'Everton vs Nottm Forest',       market:'Everton 2',         odds:2,    closingOdds:1,    result:'win',  cumPL:7.05, sport:'FOOTBALL', notes:'' },
  { id:177, date:'2025-12-07', match:'Fulham vs Crystal Palace',      market:'Draw 2',            odds:2,    closingOdds:-1,   result:'loss', cumPL:6.05, sport:'FOOTBALL', notes:'' },
  { id:178, date:'2025-12-08', match:'Man United vs Wolves',          market:'Man U 1.8',         odds:1.8,  closingOdds:null, result:'win',  cumPL:6.85, sport:'FOOTBALL', notes:'' },
  { id:179, date:'2025-12-13', match:'Liverpool vs Brighton',         market:'Brighton/Draw 2',   odds:2,    closingOdds:null, result:'loss', cumPL:5.85, sport:'FOOTBALL', notes:'' },
  { id:181, date:'2025-12-14', match:'Sunderland vs Newcastle',       market:'Sunderland 3.3',    odds:3.3,  closingOdds:null, result:'win',  cumPL:7.15, sport:'FOOTBALL', notes:'' },
  { id:182, date:'2025-12-14', match:'Leeds vs Brentford',            market:'Over 2.5',          odds:1.9,  closingOdds:null, result:'loss', cumPL:6.15, sport:'FOOTBALL', notes:'' },
  { id:183, date:'2025-12-20', match:'Tottenham vs Liverpool',        market:'Liverpool 2.1',     odds:2.1,  closingOdds:null, result:'win',  cumPL:7.25, sport:'FOOTBALL', notes:'' },
  { id:184, date:'2025-12-20', match:'Wolves vs Brentford',           market:'Wolves 3.7',        odds:3.7,  closingOdds:null, result:'loss', cumPL:6.25, sport:'FOOTBALL', notes:'Wrong bet. Wolves playing terrible.' },
  { id:185, date:'2025-12-20', match:'Newcastle vs Chelsea',          market:'Newcastle 2.7',     odds:2.7,  closingOdds:null, result:'push', cumPL:6.25, sport:'FOOTBALL', notes:'' },
  { id:186, date:'2025-12-22', match:'Fulham vs Nottm Forest',        market:'Over 2.5',          odds:2.1,  closingOdds:null, result:'loss', cumPL:5.25, sport:'FOOTBALL', notes:'Wrong bet. Too many strikers out.' },
  { id:187, date:'2025-12-20', match:'Leeds vs Crystal Palace',       market:'Crystal Palace 2.94', odds:2.94, closingOdds:null, result:'loss', cumPL:4.25, sport:'FOOTBALL', notes:'' },
  { id:188, date:'2025-12-21', match:'Aston Villa vs Man United',     market:'Over 2.5',          odds:1.7,  closingOdds:null, result:'win',  cumPL:4.95, sport:'FOOTBALL', notes:'' },
  { id:189, date:'2025-12-27', match:'Man City vs Nottm Forest',      market:'Under 2.5',         odds:2.2,  closingOdds:null, result:'loss', cumPL:3.95, sport:'FOOTBALL', notes:'' },
  { id:190, date:'2025-12-26', match:'Man United vs Newcastle',       market:'Draw No Bet 2.25',  odds:2.25, closingOdds:null, result:'win',  cumPL:4.95, sport:'FOOTBALL', notes:'' },
  { id:191, date:'2025-12-27', match:'Liverpool vs Wolves',           market:'Over 3.5',          odds:1.8,  closingOdds:null, result:'loss', cumPL:3.95, sport:'FOOTBALL', notes:'' },
  { id:192, date:'2025-12-28', match:'Sunderland vs Leeds',           market:'Sunderland +0',     odds:1.9,  closingOdds:null, result:'push', cumPL:3.95, sport:'FOOTBALL', notes:'' },
  { id:193, date:'2026-03-03', match:'Burnley vs Everton',            market:'Under 2.5',         odds:1.75, closingOdds:null, result:'win',  cumPL:4.7,  sport:'FOOTBALL', notes:'' },
  { id:194, date:'2025-12-27', match:'Chelsea vs Aston Villa',        market:'Aston Villa/Draw 2.25', odds:2.25, closingOdds:null, result:'win', cumPL:5.7, sport:'FOOTBALL', notes:'' },
  { id:195, date:'2025-12-27', match:'Chelsea vs Aston Villa',        market:'Over 2.5',          odds:1.8,  closingOdds:null, result:'win',  cumPL:6.5,  sport:'FOOTBALL', notes:'' },
  { id:196, date:'2025-12-28', match:'Crystal Palace vs Tottenham',   market:'Crystal Palace +0', odds:1.7,  closingOdds:null, result:'loss', cumPL:5.5,  sport:'FOOTBALL', notes:'' },
  { id:197, date:'2025-12-28', match:'Crystal Palace vs Tottenham',   market:'Crystal Palace/Draw 2', odds:2, closingOdds:null, result:'loss', cumPL:4.5, sport:'FOOTBALL', notes:'' },
  { id:198, date:'2025-12-30', match:'Chelsea vs Bournemouth',        market:'Draw/Chelsea 4.6',  odds:4.6,  closingOdds:null, result:'win',  cumPL:5.5,  sport:'FOOTBALL', notes:'' },
  { id:199, date:'2025-12-30', match:'Nottm Forest vs Everton',       market:'Draw/Everton 3.45', odds:3.45, closingOdds:null, result:'win',  cumPL:6.5,  sport:'FOOTBALL', notes:'' },
  { id:200, date:'2025-12-30', match:'Nottm Forest vs Everton',       market:'Under 2.5',         odds:1.75, closingOdds:null, result:'win',  cumPL:7.25, sport:'FOOTBALL', notes:'' },
  { id:201, date:'2025-12-06', match:'Arsenal vs Aston Villa',        market:'Draw/Aston Villa',  odds:5,    closingOdds:null, result:'win',  cumPL:6.25, sport:'FOOTBALL', notes:'' },
  { id:202, date:'2025-12-06', match:'Arsenal vs Aston Villa',        market:'BTTS 2.2',          odds:2.2,  closingOdds:null, result:'win',  cumPL:8.45, sport:'FOOTBALL', notes:'' },
  { id:203, date:'2025-12-06', match:'Liverpool vs Leeds',            market:'Liverpool 1.5',     odds:1.5,  closingOdds:null, result:'loss', cumPL:7.45, sport:'FOOTBALL', notes:'Should not have bet this game.' },
  { id:204, date:'2026-01-01', match:'Crystal Palace vs Fulham',      market:'Crystal Palace 2.2', odds:2.2, closingOdds:null, result:'loss', cumPL:6.45, sport:'FOOTBALL', notes:'Should not have bet this game.' },
  { id:205, date:'2026-01-03', match:'Aston Villa vs Nottm Forest',   market:'Draw 2',            odds:2,    closingOdds:null, result:'loss', cumPL:5.45, sport:'FOOTBALL', notes:'' },
  { id:206, date:'2026-01-03', match:'Aston Villa vs Nottm Forest',   market:'Under 2.5',         odds:2.1,  closingOdds:null, result:'loss', cumPL:4.45, sport:'FOOTBALL', notes:'' },
  { id:207, date:'2026-01-03', match:'Brighton vs Burnley',           market:'Draw 3',            odds:3,    closingOdds:null, result:'loss', cumPL:3.45, sport:'FOOTBALL', notes:'' },
  { id:208, date:'2026-01-03', match:'Brighton vs Burnley',           market:'Under 2.5',         odds:2.25, closingOdds:null, result:'win',  cumPL:4.7,  sport:'FOOTBALL', notes:'' },
  { id:209, date:'2026-01-03', match:'Bournemouth vs Arsenal',        market:'Draw/Arsenal 2',    odds:2,    closingOdds:null, result:'push', cumPL:4,  sport:'FOOTBALL', notes:'' },
  { id:210, date:'2026-01-03', match:'Bournemouth vs Arsenal',        market:'Over 3.5 Cards 1.5', odds:1.5, closingOdds:null, result:'win',  cumPL:4.5,  sport:'FOOTBALL', notes:'' },
  { id:211, date:'2026-01-04', match:'Man United vs Leeds',           market:'Draw 2',            odds:2,    closingOdds:null, result:'win',  cumPL:6.5,  sport:'FOOTBALL', notes:'' },
  { id:212, date:'2026-01-04', match:'Man United vs Leeds',           market:'Over 3.5 Cards 1.5', odds:1.5, closingOdds:null, result:'loss', cumPL:5.5, sport:'FOOTBALL',  notes:'' },
  { id:213, date:'2026-01-04', match:'Man City vs Chelsea',           market:'Draw 3',            odds:3,    closingOdds:null, result:'win',  cumPL:7.5,  sport:'FOOTBALL', notes:'' },
  { id:214, date:'2026-01-04', match:'Man City vs Chelsea',           market:'Over 3.5 Cards 1.5', odds:1.5, closingOdds:null, result:'win', cumPL:8,  sport:'FOOTBALL', notes:'' },
  { id:215, date:'2026-01-04', match:'Tottenham vs Sunderland',       market:'BTTS No 2',         odds:2,    closingOdds:null, result:'loss', cumPL:7,  sport:'FOOTBALL', notes:'' },
  { id:216, date:'2026-01-04', match:'Crystal Palace vs Newcastle',   market:'Draw 2',            odds:2,    closingOdds:null, result:'push', cumPL:6.5,  sport:'FOOTBALL', notes:'' },
  { id:217, date:'2026-01-07', match:'Everton vs Wolves',             market:'Draw 1.8',          odds:1.8,  closingOdds:null, result:'win',  cumPL:8.3,  sport:'FOOTBALL', notes:'' },
  { id:218, date:'2026-01-07', match:'Everton vs Wolves',             market:'Under 2.5 Goals 1.8', odds:1.8, closingOdds:null, result:'win', cumPL:10.1, sport:'FOOTBALL', notes:'' },
  { id:219, date:'2026-01-07', match:'Crystal Palace vs Aston Villa', market:'Draw/Crystal Palace 1.8', odds:1.8, closingOdds:null, result:'win', cumPL:11.9, sport:'FOOTBALL', notes:'' },
  { id:220, date:'2026-01-07', match:'Crystal Palace vs Aston Villa', market:'Under 2.5',         odds:1.95, closingOdds:null, result:'win',  cumPL:13.85, sport:'FOOTBALL', notes:'' },
  { id:221, date:'2026-01-08', match:'Arsenal vs Liverpool',          market:'Draw 2.5',          odds:2.5,  closingOdds:null, result:'win',  cumPL:16.35, sport:'FOOTBALL', notes:'' },
  { id:222, date:'2026-01-17', match:'Man United vs Man City',        market:'Under 3.5',         odds:1.7,  closingOdds:null, result:'win',  cumPL:18,  sport:'FOOTBALL', notes:'' },
  { id:223, date:'2026-01-17', match:'Man United vs Man City',        market:'Under 3.5 Cards 2.2', odds:2.2, closingOdds:null, result:'loss', cumPL:17, sport:'FOOTBALL', notes:'' },
  { id:224, date:'2026-01-17', match:'Sunderland vs Crystal Palace',  market:'Penalty Awarded 4.5', odds:4.5, closingOdds:null, result:'loss', cumPL:16, sport:'FOOTBALL', notes:'' },
  { id:225, date:'2026-01-17', match:'Leeds vs Fulham',               market:'Fulham 0/0.5',      odds:2,    closingOdds:null, result:'loss', cumPL:15,  sport:'FOOTBALL', notes:'' },
  { id:226, date:'2026-01-17', match:'Leeds vs Fulham',               market:'Under 3.5 Cards 2.3', odds:2.3, closingOdds:null, result:'loss', cumPL:14, sport:'FOOTBALL', notes:'' },
  { id:227, date:'2026-01-17', match:'Liverpool vs Burnley',          market:'Under 3.5 Cards 1.7', odds:1.7, closingOdds:null, result:'win',  cumPL:14.7,  sport:'FOOTBALL', notes:'' },
  { id:228, date:'2026-01-17', match:'Nottm Forest vs Arsenal',       market:'Draw 4.5',          odds:4.5,  closingOdds:1.8,  result:'win',  cumPL:17.5,  sport:'FOOTBALL', notes:'' },
  { id:229, date:'2026-01-18', match:'Aston Villa vs Everton',        market:'Over 2.5',          odds:2,    closingOdds:null, result:'win',  cumPL:16.5,  sport:'FOOTBALL', notes:'' },
  { id:230, date:'2026-01-17', match:'Chelsea vs Brentford',          market:'Away/Draw 2.2',     odds:2.2,  closingOdds:null, result:'loss', cumPL:15.5,  sport:'FOOTBALL', notes:'' },
  { id:233, date:'2026-01-24', match:'West Ham vs Sunderland',        market:'Under 2.5/BTTS 1.85', odds:1.85, closingOdds:null, result:'push', cumPL:15.4, sport:'FOOTBALL', notes:'' },
  { id:234, date:'2026-01-24', match:'Bournemouth vs Liverpool',      market:'Liverpool 2',       odds:2,    closingOdds:null, result:'loss', cumPL:14.3,  sport:'FOOTBALL', notes:'' },
  { id:235, date:'2026-01-24', match:'Bournemouth vs Liverpool',      market:'Over 2.5',          odds:1.6,  closingOdds:null, result:'win',  cumPL:15.3,  sport:'FOOTBALL', notes:'' },
  { id:236, date:'2026-01-25', match:'Crystal Palace vs Chelsea',     market:'Draw 3.8',          odds:3.8,  closingOdds:1.8,  result:'loss', cumPL:14.3,  sport:'FOOTBALL', notes:'' },
  { id:237, date:'2026-01-25', match:'Newcastle vs Aston Villa',      market:'Draw 4',            odds:4,    closingOdds:1.8,  result:'loss', cumPL:13.3,  sport:'FOOTBALL', notes:'' },
  { id:238, date:'2026-01-25', match:'Brentford vs Nottm Forest',     market:'Under 2.5',         odds:2,    closingOdds:null, result:'win',  cumPL:14.3,  sport:'FOOTBALL', notes:'' },
  { id:239, date:'2026-01-25', match:'Arsenal vs Man United',         market:'Draw 4.4',          odds:4.4,  closingOdds:1.8,  result:'push', cumPL:14.3,  sport:'FOOTBALL', notes:'' },
  { id:240, date:'2026-01-25', match:'Arsenal vs Man United',         market:'Under 3.5',         odds:1.5,  closingOdds:null, result:'loss', cumPL:13.3,  sport:'FOOTBALL', notes:'' },
  { id:241, date:'2026-01-31', match:'Chelsea vs West Ham',           market:'Cards Over 3.5',    odds:1.6,  closingOdds:null, result:'win',  cumPL:13.9,  sport:'FOOTBALL', notes:'' },
  { id:242, date:'2026-02-01', match:'Tottenham vs Man City',         market:'Cards Over 4.5',    odds:2.1,  closingOdds:null, result:'win',  cumPL:16,  sport:'FOOTBALL', notes:'' },
  { id:243, date:'2026-02-01', match:'Tottenham vs Man City',         market:'Draw 4.3',          odds:4.3,  closingOdds:1.8,  result:'win',  cumPL:18.5,  sport:'FOOTBALL', notes:'' },
  { id:244, date:'2026-01-31', match:'Liverpool vs Newcastle',        market:'Cards Over 3.5',    odds:1.6,  closingOdds:null, result:'win',  cumPL:19.1,  sport:'FOOTBALL', notes:'' },
  { id:245, date:'2026-01-31', match:'Liverpool vs Newcastle',        market:'Liverpool 1.85',    odds:1.85, closingOdds:null, result:'win',  cumPL:21,  sport:'FOOTBALL', notes:'' },
  { id:246, date:'2026-02-01', match:'Man United vs Fulham',          market:'Fulham 5.8',        odds:5.8,  closingOdds:1.8,  result:'loss', cumPL:20,  sport:'FOOTBALL', notes:'' },
  { id:247, date:'2026-02-01', match:'Man United vs Fulham',          market:'Over 2.5',          odds:1.75, closingOdds:null, result:'win',  cumPL:20.75, sport:'FOOTBALL', notes:'' },
  { id:248, date:'2026-02-01', match:'Nottm Forest vs Crystal Palace', market:'Crystal Palace 4.3', odds:4.3, closingOdds:1.8, result:'loss', cumPL:19.75, sport:'FOOTBALL', notes:'' },
  { id:249, date:'2026-01-31', match:'Bournemouth vs Wolves',         market:'Over 2.5',          odds:1.85, closingOdds:null, result:'loss', cumPL:18.75, sport:'FOOTBALL', notes:'' },
  { id:250, date:'2026-02-01', match:'Aston Villa vs Brentford',      market:'Over 2.5',          odds:1.8,  closingOdds:null, result:'loss', cumPL:17.75, sport:'FOOTBALL', notes:'' },
  { id:251, date:'2026-02-07', match:'Man United vs Tottenham',       market:'Draw 4.8',          odds:4.8,  closingOdds:1.8,  result:'loss', cumPL:16.75, sport:'FOOTBALL', notes:'' },
  { id:252, date:'2026-02-07', match:'Newcastle vs Brentford',        market:'Newcastle 2.1',     odds:2.1,  closingOdds:null, result:'loss', cumPL:15.75, sport:'FOOTBALL', notes:'' },
  { id:253, date:'2026-02-07', match:'Bournemouth vs Aston Villa',    market:'BTTS 1.7',          odds:1.7,  closingOdds:null, result:'win',  cumPL:16.45, sport:'FOOTBALL', notes:'' },
  { id:254, date:'2026-02-07', match:'Wolves vs Chelsea',             market:'BTTS 1.85',         odds:1.85, closingOdds:null, result:'win',  cumPL:17.25, sport:'FOOTBALL', notes:'' },
  { id:255, date:'2026-02-08', match:'Liverpool vs Man City',         market:'Draw/Liverpool 3.9', odds:3.9,  closingOdds:1.8,  result:'loss', cumPL:16.25, sport:'FOOTBALL', notes:'' },
  { id:256, date:'2026-02-10', match:'Man United vs West Ham',        market:'Draw 4.7',          odds:4.7,  closingOdds:1.7,  result:'win',  cumPL:19.25, sport:'FOOTBALL', notes:'' },
  { id:257, date:'2026-02-10', match:'Tottenham vs Newcastle',        market:'Draw 3.6',          odds:3.6,  closingOdds:null, result:'loss', cumPL:18.25, sport:'FOOTBALL', notes:'' },
  { id:258, date:'2026-02-11', match:'Wolves vs Nottm Forest',        market:'BTTS 2',            odds:2,    closingOdds:null, result:'loss', cumPL:17.25, sport:'FOOTBALL', notes:'' },
  { id:259, date:'2026-02-11', match:'Aston Villa vs Brighton',       market:'BTTS 1.8',          odds:1.8,  closingOdds:null, result:'loss', cumPL:16.25, sport:'FOOTBALL', notes:'' },
  { id:260, date:'2026-02-21', match:'Brentford vs Brighton',         market:'Brentford 2',       odds:2,    closingOdds:null, result:'loss', cumPL:15.25, sport:'FOOTBALL', notes:'' },
  { id:261, date:'2026-02-21', match:'West Ham vs Bournemouth',       market:'BTTS 1.5',          odds:1.5,  closingOdds:null, result:'loss', cumPL:14.25, sport:'FOOTBALL', notes:'' },
  { id:262, date:'2026-02-22', match:'Tottenham vs Arsenal',          market:'Draw 4.4',          odds:4.4,  closingOdds:1.7,  result:'loss', cumPL:13.25, sport:'FOOTBALL', notes:'' },
  { id:263, date:'2026-02-23', match:'Everton vs Man United',         market:'Draw 4',            odds:4,    closingOdds:1.7,  result:'loss', cumPL:12.25, sport:'FOOTBALL', notes:'' },
  { id:264, date:'2026-02-28', match:'Leeds vs Man City',             market:'Over 2.5',          odds:null, closingOdds:null, result:'loss', cumPL:11.25, sport:'FOOTBALL', notes:'' },
  { id:265, date:'2026-03-01', match:'Arsenal vs Chelsea',            market:'Draw',              odds:null, closingOdds:null, result:'loss', cumPL:10.25, sport:'FOOTBALL', notes:'' },
  { id:266, date:'2026-03-01', match:'Arsenal vs Chelsea',            market:'Over 3.5 Cards',    odds:null, closingOdds:null, result:'win',  cumPL:10.75, sport:'FOOTBALL', notes:'' },
  { id:267, date:'2026-03-05', match:'Tottenham vs Crystal Palace',   market:'Draw',              odds:null, closingOdds:null, result:'loss', cumPL:9.75, sport:'FOOTBALL', notes:'' },
];

// ─── Section 2: Sports Betting diary — structured bets Mar-Apr 2026 ──────────
// Appended to LEGACY_BETS. Dates stored as Australian DD/MM in Excel (swapped
// by Excel's US-locale serial parser — all corrected here to true AU dates).
LEGACY_BETS.push(
  { id:283, date:'2026-03-06', match:'Dolphins vs Souths',                  market:'Over 48.5',        odds:1.9,  closingOdds:1.9,  result:'win',  cumPL:16.4,  sport:'NRL',      notes:'' },
  { id:284, date:'2026-03-12', match:'Carlton vs Richmond',                  market:'Under 178.5',      odds:1.9,  closingOdds:1.9,  result:'win',  cumPL:17.3,  sport:'AFL',      notes:'' },
  { id:285, date:'2026-03-13', match:'Essendon vs Hawthorn',                market:'Over 183.5',        odds:1.9,  closingOdds:1.9,  result:'win',  cumPL:18.2,  sport:'AFL',      notes:'' },
  { id:286, date:'2026-03-14', match:'Penrith vs Cronulla',                  market:'Under 44.5',       odds:1.9,  closingOdds:1.9,  result:'win',  cumPL:19.1,  sport:'NRL',      notes:'' },
  { id:287, date:'2026-03-14', match:'Man United vs Aston Villa',            market:'Man U 1.74',       odds:1.7,  closingOdds:null, result:'win',  cumPL:19.8,  sport:'FOOTBALL', notes:'' },
  { id:288, date:'2026-03-14', match:'Sydney vs Brisbane',                   market:'Win',              odds:3.2,  closingOdds:3.2,  result:'loss', cumPL:18.8,  sport:'AFL',      notes:'' },
  { id:289, date:'2026-03-14', match:'Sydney vs Brisbane',                   market:'Under 190.5',      odds:1.95, closingOdds:1.95, result:'win',  cumPL:19.75, sport:'AFL',      notes:'' },
  { id:290, date:'2026-03-15', match:'Melbourne vs St Kilda',                market:'Under 180.5',      odds:1.9,  closingOdds:1.9,  result:'loss', cumPL:18.75, sport:'AFL',      notes:'Overpriced for both teams. Bottom 8, cagey. MCG is a big factor.' },
  { id:291, date:'2026-03-19', match:'Hawthorn vs Sydney',                   market:'Line 10.5 Sydney', odds:1.9,  closingOdds:1.9,  result:'loss', cumPL:17.75, sport:'AFL',      notes:'Sydney in rare form. If going to win at MCG it was now.' },
  { id:292, date:'2026-03-22', match:'Brighton vs Liverpool',                market:'Under 2.5',        odds:2.3,  closingOdds:null, result:'loss', cumPL:16.75, sport:'FOOTBALL', notes:'Early kickoff, low morale, Liverpool not converting.' },
  { id:293, date:'2026-03-22', match:'Brighton vs Liverpool',                market:'Draw',             odds:3.85, closingOdds:null, result:'loss', cumPL:15.75, sport:'FOOTBALL', notes:'Liverpool afraid to lose, conceding late goals.' },
  { id:294, date:'2026-03-22', match:'Newcastle vs Sunderland',              market:'Draw',             odds:4.2,  closingOdds:null, result:'loss', cumPL:14.85, sport:'FOOTBALL', notes:'Sunderland must get points. Derby. Both afraid to lose.' },
  { id:295, date:'2026-03-19', match:'Tottenham vs Atletico Madrid',         market:'Under 3.5 Cards',  odds:2.0,  closingOdds:2.0,  result:'loss', cumPL:13.75, sport:'FOOTBALL', notes:'' },
  { id:296, date:'2026-03-19', match:'Canberra vs Canterbury',               market:'Under 49.5',       odds:1.9,  closingOdds:null, result:'win',  cumPL:14.65, sport:'NRL',      notes:'' },
  { id:297, date:'2026-03-22', match:'West Coast Eagles vs North Melbourne', market:'Under 179.5',      odds:1.9,  closingOdds:null, result:'loss', cumPL:13.75, sport:'AFL',      notes:'' },
  { id:298, date:'2026-03-22', match:'North QLD vs Gold Coast',              market:'Under 57.5',       odds:1.9,  closingOdds:null, result:'win',  cumPL:14.75, sport:'NRL',      notes:'' },
  { id:299, date:'2026-03-26', match:'Geelong vs Adelaide',                  market:'Under 179.5',      odds:1.9,  closingOdds:null, result:'win',  cumPL:15.65, sport:'AFL',      notes:'' },
  { id:300, date:'2026-03-27', match:'Collingwood vs GWS',                   market:'Under 179.6',      odds:1.9,  closingOdds:null, result:'win',  cumPL:16.55, sport:'AFL',      notes:'' },
  { id:301, date:'2026-03-28', match:'Carlton vs North Melbourne',           market:'Under 180.5',      odds:1.9,  closingOdds:null, result:'win',  cumPL:17.45, sport:'AFL',      notes:'' },
  { id:302, date:'2026-03-27', match:'Australia vs Cameroon',                market:'Under 2.5',        odds:1.75, closingOdds:null, result:'win',  cumPL:18.2,  sport:'FOOTBALL', notes:'' },
  { id:303, date:'2026-03-29', match:'Penrith vs Parramatta',                market:'Under 47.5',       odds:1.95, closingOdds:null, result:'loss', cumPL:17.2,  sport:'NRL',      notes:'' },
  { id:304, date:'2026-04-03', match:'Brisbane vs Collingwood',              market:'Over 176.5',       odds:1.9,  closingOdds:null, result:'win',  cumPL:18.1,  sport:'AFL',      notes:'' },
  { id:305, date:'2026-04-04', match:'St George vs North Queensland',        market:'Under 49.5',       odds:1.8,  closingOdds:null, result:'win',  cumPL:18.9,  sport:'NRL',      notes:'' },
  { id:306, date:'2026-04-05', match:'Parramatta vs Wests Tigers',           market:'Tigers Win',       odds:2.0,  closingOdds:null, result:'win',  cumPL:19.9,  sport:'NRL',      notes:'' },
  { id:307, date:'2026-04-10', match:'Collingwood vs Fremantle',             market:'Under 174.5',      odds:1.9,  closingOdds:null, result:'win',  cumPL:20.8,  sport:'AFL',      notes:'' },
  { id:308, date:'2026-04-09', match:'PSG vs Liverpool',                     market:'PSG Win',          odds:1.75, closingOdds:null, result:'win',  cumPL:21.55, sport:'FOOTBALL', notes:'' },
  { id:309, date:'2026-04-11', match:'Sunderland vs Tottenham',              market:'Tottenham Win',    odds:2.7,  closingOdds:null, result:'loss', cumPL:20.55, sport:'FOOTBALL', notes:'' },
  { id:310, date:'2026-04-09', match:'Canterbury vs Penrith',                market:'Bulldogs +18.5',   odds:1.9,  closingOdds:null, result:'win',  cumPL:21.45, sport:'NRL',      notes:'' },
  { id:311, date:'2026-04-11', match:'North Melbourne vs Brisbane',          market:'Under 192.5',      odds:1.9,  closingOdds:null, result:'win',  cumPL:22.45, sport:'AFL',      notes:'' },
  { id:312, date:'2026-04-11', match:'Hawthorn vs Western Bulldogs',         market:'Under 182.5',      odds:1.9,  closingOdds:null, result:'win',  cumPL:23.45, sport:'AFL',      notes:'' },
  { id:313, date:'2026-04-12', match:'Parramatta vs Gold Coast',             market:'Under 49.5',       odds:1.9,  closingOdds:null, result:'loss', cumPL:22.45, sport:'NRL',      notes:'' },
  { id:314, date:'2026-04-12', match:'Wests Tigers vs Newcastle',            market:'Under 49.5',       odds:1.9,  closingOdds:null, result:'loss', cumPL:21.45, sport:'NRL',      notes:'' },
  { id:315, date:'2026-04-12', match:'GWS vs Richmond',                      market:'Under 178.5',      odds:1.9,  closingOdds:null, result:'loss', cumPL:20.45, sport:'AFL',      notes:'' },
  { id:316, date:'2026-04-12', match:'Chelsea vs Man City',                  market:'Man City Win',     odds:2.0,  closingOdds:null, result:'win',  cumPL:21.55, sport:'FOOTBALL', notes:'' },
  { id:317, date:'2026-04-17', match:'Geelong vs Western Bulldogs',          market:'Geelong -10.5',    odds:1.9,  closingOdds:null, result:'win',  cumPL:22.65, sport:'AFL',      notes:'' },
  { id:318, date:'2026-04-17', match:'Tottenham vs Brighton',                market:'Over 2.5',         odds:1.7,  closingOdds:null, result:'win',  cumPL:23.35, sport:'FOOTBALL', notes:'' },
  { id:319, date:'2026-04-17', match:'Chelsea vs Man United',                market:'Under 2.5',        odds:2.3,  closingOdds:null, result:'win',  cumPL:24.65, sport:'FOOTBALL', notes:'' },
  { id:320, date:'2026-04-17', match:'Everton vs Liverpool',                 market:'Under 2.5',        odds:2.0,  closingOdds:null, result:'loss', cumPL:23.65, sport:'FOOTBALL', notes:'' },
  { id:321, date:'2026-04-17', match:'Man City vs Arsenal',                  market:'Man City Win',     odds:2.0,  closingOdds:null, result:'win',  cumPL:24.55, sport:'FOOTBALL', notes:'' },
  { id:322, date:'2026-04-25', match:'Wolves vs Tottenham',                  market:'Tottenham Win',    odds:1.75, closingOdds:null, result:'win',  cumPL:25.3,  sport:'FOOTBALL', notes:'' },
  { id:323, date:'2026-04-25', match:'Fulham vs Aston Villa',                market:'Over 2.5',         odds:2.0,  closingOdds:null, result:'loss', cumPL:24.3,  sport:'FOOTBALL', notes:'' },
  { id:324, date:'2026-04-25', match:'Liverpool vs Crystal Palace',          market:'Under 2.5',        odds:2.0,  closingOdds:null, result:'loss', cumPL:23.3,  sport:'FOOTBALL', notes:'' },
  { id:325, date:'2026-04-25', match:'Brisbane vs Adelaide Crows',           market:'Under 189.5',      odds:2.0,  closingOdds:null, result:'loss', cumPL:22.3,  sport:'AFL',      notes:'' },
  { id:326, date:'2026-05-01', match:'Western Bulldogs vs Fremantle',         market:'Western Bulldogs', odds:3.21, closingOdds:null, result:'loss', cumPL:21.64, sport:'AFL',      notes:'Actual bet log. Stake $33. Fremantle won 114-102.' },
  { id:327, date:'2026-05-01', match:'Adelaide vs Port Adelaide',             market:'Adelaide -9.5',    odds:1.89, closingOdds:null, result:'loss', cumPL:20.64, sport:'AFL',      notes:'Actual bet log. Stake $50. Adelaide won by 1 but did not cover.' },
  { id:328, date:'2026-05-01', match:'Dolphins vs Melbourne Storm',           market:'Under 54.5',       odds:1.84, closingOdds:null, result:'win',  cumPL:21.48, sport:'NRL',      notes:'Actual bet log. Stake $50. Dolphins won 28-10, total 38.' },
  { id:329, date:'2026-05-01', match:'Dolphins vs Melbourne Storm',           market:'Dolphins -3.5',    odds:1.89, closingOdds:null, result:'win',  cumPL:22.37, sport:'NRL',      notes:'Actual bet log. Stake $50. Dolphins covered by 18.' },
  { id:330, date:'2026-05-02', match:'Carlton vs St Kilda',                   market:'Carlton',          odds:2.55, closingOdds:null, result:'loss', cumPL:21.57, sport:'AFL',      notes:'Actual bet log. Stake $40. St Kilda won.' },
  { id:331, date:'2026-05-02', match:'Carlton vs St Kilda',                   market:'Under 183.5',      odds:1.89, closingOdds:null, result:'win',  cumPL:22.46, sport:'AFL',      notes:'Actual bet log. Stake $50. Under landed.' },
  { id:332, date:'2026-05-03', match:'Cronulla Sharks vs Wests Tigers',       market:'Cronulla Win',     odds:null, closingOdds:null, result:'win',  cumPL:23.46, sport:'NRL',      notes:'Missing weekend ticket added manually. Cronulla won 52-10.' },
);

// ─── NRL Betting Model (separate tab) ────────────────────────────────────────
// 26 NRL-only bets. predictedLine = model's fair-odds or predicted total score.
// plUnits = individual bet P&L per 1 unit staked. runningTotal = cumulative.
export const MODEL_BETS: ModelBet[] = [
  { id:1,  date:'2026-03-19', match:'Canberra Raiders vs Canterbury Bulldogs', market:'Canberra -1.5',     predictedLine:1.74, takenPrice:1.9,  closingPrice:1.86, result:'loss', plUnits:-1,    runningTotal:-1    },
  { id:2,  date:'2026-03-21', match:'Parramatta vs St George',                 market:'Parramatta Win',    predictedLine:1.35, takenPrice:1.5,  closingPrice:1.5,  result:'win',  plUnits:0.5,   runningTotal:-0.5  },
  { id:3,  date:'2026-03-20', match:'Sydney Roosters vs Penrith Panthers',      market:'Under 45.5',        predictedLine:42,   takenPrice:1.95, closingPrice:1.95, result:'win',  plUnits:0.95,  runningTotal:0.45  },
  { id:4,  date:'2026-03-22', match:'Parramatta vs St George',                 market:'Under 52.5',        predictedLine:46,   takenPrice:1.95, closingPrice:1.95, result:'win',  plUnits:0.95,  runningTotal:1.4   },
  { id:5,  date:'2026-03-22', match:'Cowboys vs Titans',                       market:'Cowboys +3.5',      predictedLine:9,    takenPrice:1.9,  closingPrice:1.95, result:'win',  plUnits:0.9,   runningTotal:2.35  },
  { id:6,  date:'2026-03-21', match:'Newcastle vs Warriors',                   market:'Warriors Win',      predictedLine:1.34, takenPrice:1.5,  closingPrice:1.5,  result:'win',  plUnits:0.5,   runningTotal:2.85  },
  { id:7,  date:'2026-03-21', match:'Souths vs Tigers',                        market:'Under 52.5',        predictedLine:null, takenPrice:1.9,  closingPrice:1.9,  result:'win',  plUnits:0.9,   runningTotal:3.75  },
  { id:8,  date:'2026-03-26', match:'Manly vs Roosters',                       market:'Manly Win',         predictedLine:2.25, takenPrice:2.85, closingPrice:2.5,  result:'loss', plUnits:-1,    runningTotal:2.75  },
  { id:9,  date:'2026-03-27', match:'Broncos vs Dolphins',                     market:'Dolphins +6.5',     predictedLine:1.7,  takenPrice:2.0,  closingPrice:2.0,  result:'loss', plUnits:-1,    runningTotal:1.75  },
  { id:10, date:'2026-03-28', match:'Raiders vs Cronulla',                     market:'Raiders -1.5',      predictedLine:1.7,  takenPrice:2.0,  closingPrice:2.0,  result:'loss', plUnits:-1,    runningTotal:0.75  },
  { id:11, date:'2026-04-04', match:'St George vs Cowboys',                    market:'St George Win',     predictedLine:2.2,  takenPrice:2.05, closingPrice:2.05, result:'loss', plUnits:-1,    runningTotal:-0.25 },
  { id:12, date:'2026-04-04', match:'Newcastle vs Canberra',                   market:'Newcastle Win',     predictedLine:2.0,  takenPrice:2.4,  closingPrice:2.4,  result:'win',  plUnits:1.4,   runningTotal:1.15  },
  { id:13, date:'2026-04-05', match:'Sharks vs Warriors',                      market:'Warriors Win',      predictedLine:2.0,  takenPrice:2.36, closingPrice:2.3,  result:'loss', plUnits:-1,    runningTotal:0.15  },
  { id:14, date:'2026-04-04', match:'Broncos vs Cowboys',                      market:'Broncos Win',       predictedLine:1.3,  takenPrice:1.9,  closingPrice:1.9,  result:'loss', plUnits:-1,    runningTotal:-0.85 },
  { id:15, date:'2026-04-05', match:'Melbourne vs Warriors',                   market:'Melbourne Win',     predictedLine:1.3,  takenPrice:1.5,  closingPrice:1.35, result:'loss', plUnits:-1,    runningTotal:-1.85 },
  { id:16, date:'2026-04-06', match:'Sharks vs Roosters',                      market:'Sharks Win',        predictedLine:1.7,  takenPrice:2.05, closingPrice:2.1,  result:'loss', plUnits:-1,    runningTotal:-2.85 },
  { id:17, date:'2026-04-10', match:'Broncos vs Cowboys',                      market:'Under 49.5',        predictedLine:2.0,  takenPrice:2.0,  closingPrice:2.0,  result:'loss', plUnits:-1,    runningTotal:-3.85 },
  { id:18, date:'2026-04-10', match:'Parramatta vs Gold Coast',                market:'Parramatta Win',    predictedLine:1.7,  takenPrice:1.8,  closingPrice:1.65, result:'loss', plUnits:-1,    runningTotal:-4.85 },
  { id:19, date:'2026-04-16', match:'North Queensland vs Manly',               market:'Under 53.5',        predictedLine:50.5, takenPrice:1.9,  closingPrice:null, result:'win',  plUnits:0.9,   runningTotal:-3.95 },
  { id:20, date:'2026-04-16', match:'Dolphins vs Penrith',                     market:'Under 51.5',        predictedLine:48.5, takenPrice:1.9,  closingPrice:null, result:'win',  plUnits:0.9,   runningTotal:-3.05 },
  { id:21, date:'2026-04-16', match:'Parramatta vs Canterbury (+13.5)',        market:'Parramatta +13.5',  predictedLine:6.5,  takenPrice:1.9,  closingPrice:null, result:'win',  plUnits:0.9,   runningTotal:-2.15 },
  { id:22, date:'2026-04-16', match:'Rabbitohs vs St George',                  market:'Under 51.5',        predictedLine:null, takenPrice:1.9,  closingPrice:null, result:'win',  plUnits:0.9,   runningTotal:-1.25 },
  { id:23, date:'2026-04-16', match:'Wests Tigers vs Brisbane',                market:'Brisbane Win',      predictedLine:2.0,  takenPrice:2.5,  closingPrice:null, result:'win',  plUnits:1.5,   runningTotal:0.25  },
  { id:24, date:'2026-04-24', match:'Wests Tigers vs Canberra',                market:'Canberra Win',      predictedLine:2.0,  takenPrice:2.0,  closingPrice:null, result:'loss', plUnits:-1,    runningTotal:-0.75 },
  { id:25, date:'',           match:'TBD',                                     market:'',                  predictedLine:null, takenPrice:null, closingPrice:null, result:'win',  plUnits:1.5,   runningTotal:0.75  },
  { id:26, date:'',           match:'TBD',                                     market:'',                  predictedLine:null, takenPrice:null, closingPrice:null, result:'loss', plUnits:-1,    runningTotal:-0.25 },
];
